### ISSUE TITLE
add 'active' column to all existing clients' meter tables and populate

### ISSUE THREAD

**Issue by megan-conexon** [Conexon/Data-Standardization#16]
@elizabethsanner 

we need to add the new column `active` to all existing clients and populate it.

this field should be `long integer` in Arc and should only allow the values 0 and 1.

0 = inactive meters and 1 = active meters

@LuisaConexon is a good person to go to for finding this information (although i think you already do this for feasibility).

all of these clients have a field that differentiate if a meter is active or not, could you start here? happy to help

- [ ] Ark Valley | acctstatus
- [ ] Canadian Valley | gs_servi_2
- [ ] ECOEC | gs_servi_2
- [ ] Coast | acctstatus
- [ ] Cookson | gs_servi_2
- [ ] Coos | acctstatus
- [ ] Delta | acctstatus
- [ ] Forked Deer | acctstatus
- [ ] KREM | acctstatus
- [ ] MCEC | gs_service_status
- [ ] MidSouth | acctstatus
- [ ] Osage Valley | gs_servi_2
- [x] Northeast | acctstatus
- [ ] Petit Jean | gs_servi_2
- [ ] SEMO | SERVSTATUS
- [ ] SCAEC | gs_servi_2
- [ ] Singing River | gs_servi_2
- [ ] TriCounty SC | accstatus
- [ ] TriCounty GA | accstatus

cc: @feomike @LuisaConexon @AdamConexon

**Comment by elizabethsanner** [comment]
@megan-conexon Luisa brought this up in our meeting last week and sent an email to all the designers/leads on these coops.  They will be creating the active column and updating it with the relevant info. I'll be QC'ing when they are finished.  We asked that they have this done mid-next week (~april 1 at the latest).

**Comment by megan-conexon** [comment]
closing this. this issue is being worked on here... https://github.com/Conexon/data-processing/issues/157
